### PR TITLE
`homeassistant-core` and `wyoming` container docs update, custom wake word

### PR DESCRIPTION
**Pull request by ms1design**
Hi,

- Final changes to `homeassistant-core` and `wyoming` container docs
- Add example custom wake word model for `wyoming-openwakeword`

### CODE REVIEW

**Comment by dusty-nv** [comment]
@ms1design `wyoming-openwakeword` is now failing to build on JP5 / L4T R35.4.1 because of `tflite-runtime-nightly` dependency - do you know what changed?

```bash
+ echo 'wyoming-openwakeword: 1.10.0'
+ pip3 install --no-cache-dir --extra-index-url https://www.piwheels.org/simple 'wyoming-openwakeword @ https://github.com/rhasspy/wyoming-openwakeword/archive/refs/tags/v1.10.0.tar.gz'
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting wyoming-openwakeword@ https://github.com/rhasspy/wyoming-openwakeword/archive/refs/tags/v1.10.0.tar.gz
  Downloading https://github.com/rhasspy/wyoming-openwakeword/archive/refs/tags/v1.10.0.tar.gz
     | 5.3 MB 22.7 MB/s 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
INFO: pip is looking at multiple versions of wyoming-openwakeword to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement tflite-runtime-nightly (from wyoming-openwakeword) (from versions: none)
ERROR: No matching distribution found for tflite-runtime-nightly
```

**Comment by ms1design** [comment]
@dusty-nv I have not builded it on JP5 / L4T R35.4.1 unfortunately. Need to do the bday present unboxing 🫣 to try on that with JP5, but really didn’t had much free time for that last days.

**Comment by dusty-nv** [comment]
Oh yea, don't worry about setting up for JP5/ect - I will handle that (you might just wanna wait to flash that unit for JP6 GA to come out any day now...) - I was just wondering if you knew why it now needs TFLite and if that's possible to resolve or disable on Ubuntu 18.04

**Comment by ms1design** [comment]
Oh yes that too, I'm not with a hassle with unboxing also because I'm waiting for JP6 GA 👍 `wyoming-openwakeword` doesn't use `cuda` yet 🙈 I have that on my [todo list](https://github.com/dusty-nv/jetson-containers/tree/master/packages/smart-home/wyoming/openwakeword#todos) in docs. I think we just need to build it against `onnxruntime`, but I did not have much time to check if it requires any patching in the `openwakeword` codebase.

**Comment by dusty-nv** [comment]
wyoming-openwakeword built on JP5 before (https://hub.docker.com/r/dustynv/wyoming-openwakeword/tags) and I didn't see any changes to the dockerfile in this PR related to TFLite - maybe the change came from upstream?

**Comment by dusty-nv** [comment]
Regardless, merged this and the docs updates into master awhile.  All ready for tomorrow :grinning:

**Comment by dusty-nv** [comment]
Nevermind about JP5, other of the wyoming containers are failing too, and overall its probably unsustainable to support both JP5/JP6 (for Wyoming at least), so let's just focus on JP6 support for Wyoming :+1:

**Comment by ms1design** [comment]
I will investigate that later 👍

**Pull request merged**
