### PR TITLE
[jp6] Adding OLED package

### PR DESCRIPTION
**Pull request by tokk-nv**
Adding package:
- hardware
    - oled

### CODE REVIEW

**Comment by tokk-nv** [comment]
Added the following
- `/start_oled_server` (so that it can be used as a base for other containers)

Limitation
- Data retrieval hardcoded (eventually to be moved to using `jtop`?)
  - `power_mode()`, `power_usage()` return fixed values
- Does not clear out OLED display upon exiting (eventually to handle SIGINT?)

Tested with
- [Adafruit PiOLED](https://www.adafruit.com/product/3527)

Tested on
- Jetson Orin Nano Developer Kit running JetPack 6.0 GA
- Jetson Xavier NX Developer Kit running JetPack 5.1.1

image

**Comment by ms1design** [comment]
@dusty-nv @tokk-nv This is something nice. I wonder if in future we could benefit from this work and use it do deliver Jetson sensor data point into Home Assistant instance using custom integration?

**Comment by dusty-nv** [comment]
Sounds good @ms1design!  Yes, it is a nifty little widget for headless systems.

@tokk-nv can you rebase this against latest dev branch by copying `hardware/oled` when you are ready for it to be merged?

**Comment by tokk-nv** [comment]
Hi @dusty-nv 
I've merged the latest of your dev branch into this fork branch of mine, so I believe this is ready to be merged.

**Comment by dusty-nv** [comment]
@tokk-nv it changes lots of unrelated files- should I just pick `hardware/oled` for you branch, or were there other required changes?

**Comment by tokk-nv** [comment]
Yes, the real changes are on ly under the `hardware/oled` directory.

**Comment by dusty-nv** [comment]
Manually cherry-picked this in https://github.com/dusty-nv/jetson-containers/commit/5ca13d3719b0d0d091183177ff1527a8efaf1078 - thanks @tokk-nv

**Pull request closed without merging**
