### PR TITLE
fix(homeassistant-core): Fix onboarding flow error due to translation issues #689712

### PR DESCRIPTION
**Pull request by ms1design**
Hi,

Was a bit bored waiting, so I decided to do patch to fix https://community.home-assistant.io/t/new-install-onboarding-failedkeyerror-component-onboarding-area-living-room/689712 to unstuck the onboarding process. Now Home Assistant Core works on Jetson.

### CODE REVIEW

**Comment by dusty-nv** [comment]
Nice!  Thanks @ms1design - are there any special tricks needed to run this for doing a new HomeAssistant installation, or should I just basically proceed by following their documentation?

**Comment by ms1design** [comment]
@dusty-nv I was able to go through onboarding process and tested the Assist in browser. It worked. I assume that rest should also work :) If nit then we start to worry ;)

**Comment by dusty-nv** [comment]
@ms1design trying to build this for dockerhub, and there is an additional `ffmpeg` container you defined in the depends that is missing and I can't find from the previous PR's you submitted - if you have it locally, can you push the PR for that?   assuming it's more than just `apt install ffmpeg`

**Comment by ms1design** [comment]
@dusty-nv true, sorry about that. `PR` is on the way.

**Pull request merged**
