### PR TITLE
Upgrade `flash-attention` to `2.5.7`, fix `text-generation-webui` container

### PR DESCRIPTION
**Pull request by ms1design**
Hi,

- Upgrade `flash-attention` to `2.5.7`
- Fix `text-generation-webui` container

### CODE REVIEW

**Comment by dusty-nv** [comment]
@ms1design can you comment on why to remove the `auto_awq` patch from the oobabooga's requirements.txt?

auto_awq container gets added to text-gen-webui container on JP6:   https://github.com/dusty-nv/jetson-containers/blob/97fd4fcc3a896a9074dbeef6e78cf01a910d944b/packages/llm/text-generation-webui/config.py#L32

So I remove that from requirements.txt so it doesn't go out installing some other version, but rather keeps the version from container.   It looks like this is now `autoawq==0.2.3; platform_system == "Linux" or platform_system == "Windows"` in their requirements.txt

I'm guessing you hit some issue with this

**Comment by ms1design** [comment]
Missed that you migrated it to `config.py`, restored.

**Comment by dusty-nv** [comment]
Thanks @ms1design - I added a config.py to flash-attention container to support proper versioning in [98952b4](https://github.com/dusty-nv/jetson-containers/commit/98952b4c1d75240aea10e261b8db11ef21b6a333)

**Comment by dusty-nv** [comment]
[`flash_attn-2.5.7-cp310-cp310-linux_aarch64.whl`](http://jetson.webredirect.org/jp6/cu122/flash-attn/2.5.7)

**Pull request merged**
