### PR TITLE
add bondcpp dependancies

### PR DESCRIPTION
**Pull request by amfern**

### CODE REVIEW

**Comment by amfern** [comment]
I need bandcpp to compile navigation2 pacakges @dusty-nv

**Comment by dusty-nv** [comment]
I recommend adding this to the container that you are building for the navigation2 packages.

See here for an example of how to install additional ROS packages from source using `rosinstall_generator` on top of the existing ROS installation in the container:

https://github.com/dusty-nv/jetson-containers/blob/16ad22ccdc8b020f7bae0686bf167116d6d243fa/Dockerfile.ros.slam#L161

**Comment by amfern** [comment]
I will do that for my container, it does better then what i have till now.
What do you think about adding container with navigation2 to this repo? i think many people will like it

**Comment by dusty-nv** [comment]
> What do you think about adding container with navigation2 to this repo? i think many people will like it

My colleague just uses the official ROS container for nav2 for ARM/aarch64 on Jetson - since nav2 doesn't use CUDA, it doesn't need to be a special container built.  So in the meantime you can try this.

However I will give building nav2 from source a try, because I now have these SLAM containers, and it would be good to have nav2 as a base for those.

**Comment by amfern** [comment]
yes, i agree.

**Comment by Gianstiff** [comment]
> > What do you think about adding container with navigation2 to this repo? i think many people will like it
> 
> My colleague just uses the official ROS container for nav2 for ARM/aarch64 on Jetson - since nav2 doesn't use CUDA, it doesn't need to be a special container built. So in the meantime you can try this.
> 
> However I will give building nav2 from source a try, because I now have these SLAM containers, and it would be good to have nav2 as a base for those.

Have you had any experience with that?
Actually I was trying to compile the nav2 libraries inside the container but I'm having trouble for all dependencies resolution.

**Comment by amfern** [comment]
I end up compiling just the packages I need from nav2. Also, i have transition to use this docker instead https://github.com/timongentzsch/Jetson_Ubuntu20_Images, this is actually ubuntu20 for jetson

**Pull request closed without merging**
