### PR TITLE
Mamba #447

### PR DESCRIPTION
**Pull request by johnnynunez**
#447

casualconv1d: https://github.com/Dao-AILab/causal-conv1d
mamba original paper: https://github.com/state-spaces/mamba
MambaVision: https://github.com/NVlabs/MambaVision
Complete Suite of VideoMamba: https://github.com/OpenGVLab/video-mamba-suite 
cobra(llava rival): https://github.com/h-zhao1997/cobra
VideoMambaSuite:
image

### CODE REVIEW

**Comment by johnnynunez** [comment]
@dusty-nv feel free to organize the folders inside jetson-containers.
mamba depends from causalconv1d.
an all repositories that use mamba depends of mamba like videosuite or mambavision
all is build with cuda(this folders need a benchmark).
Now we can use LLM models that use mamba :) as you can see on my test.py
also works with images or video

**Comment by johnnynunez** [comment]
Benchmark:
image
Captura de pantalla 2024-09-05 a las 11 50 14

2 scenario:
image

Captura de pantalla 2024-09-05 a las 11 51 44

**Comment by dusty-nv** [comment]
Thanks @johnnynunez, looks like another fun one!  🤣 🐍

**Comment by johnnynunez** [comment]
> Thanks @johnnynunez, looks like another fun one! 🤣 🐍

Please see the spam of my messages JAJAJ. I think I need your help because this is going too fast.

**Comment by dusty-nv** [comment]
Haha that does seem fast!  Is it producing valid/coherent output?   That would be great 👍

**Comment by johnnynunez** [comment]
> Haha that does seem fast! Is it producing valid/coherent output? That would be great 👍

it is the original benchmark from mamba:
https://github.com/state-spaces/mamba/blob/main/benchmarks/benchmark_generation_mamba_simple.py

**Comment by johnnynunez** [comment]
@dusty-nv if you can upload casual-conv1d wheel and mamba-ssm wheel, I will thank you

**Comment by dusty-nv** [comment]
@johnnynunez I will start trying to build these tonight/tomorrow and push the wheels & containers 👍

**Pull request merged**
