### PR TITLE
Add `whisperx` package

### PR DESCRIPTION
**Pull request by tokk-nv**
Adding `whisperx`, `faster-whisper` and `ctraslate2` packages.

- `whisperx` package 
  - which depends on `faster-whisper` package
    - which depends on  `ctraslate2` package

### CODE REVIEW

**Comment by johnnynunez** [comment]
@dusty-nv I've check it and works well. Only one thing is that it has been carefully with ctranslate2 build python packages with the directory to build it.
Or fixed with:
```python
include_dirs = [pybind11.get_include(), '/usr/local/include/ctranslate2']
library_dirs = ['/usr/local/lib']
```
Or fixed with change:
CMAKE_INSTALL_PREFIX
from https://opennmt.net/CTranslate2/installation.html#install-from-sources

**Comment by tokk-nv** [comment]
Hi @johnnynunez 
Thank you for checking.
Will you explain to me what you are proposing regarding the CTranslate2 build?
I believe it found `cmake` fine, and it also built the Python wrapper.

**Comment by johnnynunez** [comment]
> Hi @johnnynunez Thank you for checking. Will you explain to me what you are proposing regarding the CTranslate2 build? I believe it found `cmake` fine, and it also built the Python wrapper.

Yes because you use containers. If it's compile outside using for example miniconda, there is an error, from Ctranslate2 repository.

**Comment by tokk-nv** [comment]
ok, thank you.

**Pull request merged**
